### ISSUE TITLE
Error while importing protos: illegal value '['

### ISSUE THREAD

**Issue by xmlking** [uw-labs/bloomrpc#115] opened 2019-09-03 07:18 UTC
Unable to import  my proto https://github.com/xmlking/micro-starter-kit/blob/develop/srv/account/proto/account/account.proto

Error: Error while importing protos
illegal value '[' (/micro-starter-kit/srv/account/proto/account/account.proto, line 132)

looks like it doesn't  like `[(validate.rules).string = {in: ["M", "F"]}];`

```protobuf
message ProfileRequest {
    google.protobuf.StringValue id = 1 [(validate.rules).string.uuid = true]; // Not Working
    google.protobuf.StringValue userId = 2 [(validate.rules).string.uuid = true]; // Not Working
    google.protobuf.StringValue tz = 3;
    google.protobuf.StringValue avatar = 4 [(validate.rules).string.uri_ref = true];
    google.protobuf.StringValue gender = 5 [(validate.rules).string = {in: ["M", "F"]}];
    google.protobuf.Timestamp birthday = 6 [(validate.rules).timestamp.lt_now = true];
}
```

**Comment by fenos** [comment] 2019-09-20 15:36
Unfortunately that is a limitation of `protobuf.js` the issue is tracked from here:
https://github.com/protobufjs/protobuf.js/pull/1256

We are thinking to use a forked version of `protobuf.js` until this is merged in

**Comment by xmlking** [comment] 2019-09-20 21:02
`protobuf.js`  last   commit is  `Jun 24` 
 we might has to to fork and use here.

**Comment by schaudhary111** [comment] 2019-10-01 12:22
I am facing the same issue, any workaround or hacks for time being.

**Comment by jackielii** [comment] 2020-11-11 15:23
dup of #96

**Closed by jackielii** 2020-11-11 15:23 UTC
Labels: protobuf.js/unsupported
