### ISSUE TITLE
keys that end with '-bin' must have Buffer values

### ISSUE THREAD

**Issue by tonyboxes** [uw-labs/bloomrpc#105] opened 2019-07-30 03:10 UTC
Build a binary metadata to base64:
```
{
    "x-metadata-bin": "Cgh0ZXN0X2tleRIIbW9iaV9hcHAaBmRldmljZSAB"   
}
```
Get this error:
```
Error constructing the request
keys that end with '-bin' must have Buffer values
```

**Comment by fenos** [comment] 2019-07-30 07:57
@tonyboxes interesting, thanks for pointing this out.

This will be fixed in the next coming release

**Comment by HunterEl** [comment] 2019-08-01 22:02
Just ran into this issue as well. Thanks for the update, @fenos!

**Comment by tonyboxes** [comment] 2019-08-02 01:13
Can you add debugging information, such as request header and response header information.

**Comment by HunterEl** [comment] 2019-08-02 01:48
@tonyboxes 
```{
    "authorization-bin": "{insert hex string of data}"   
}
 Prompts me with the error message: 

`Error constructing the request
keys that end with '-bin' must have Buffer values`
```

**Comment by HunterEl** [comment] 2019-08-02 01:50
for context, using a CLI tool with the same request and meta-data information works as intended.

**Closed** 2019-09-20 15:44 UTC
Labels: bug

**Comment by tonyboxes** [comment] 2019-12-26 09:44
Please release this version？
