### ISSUE TITLE
Unable to connect with SSL enabled gRPC Server

### ISSUE THREAD

**Issue by mohanavijay** [uw-labs/bloomrpc#100] opened 2019-07-21 10:52 UTC
I'm unable to connect with SSL enabled gRPC server using bloomrpc

https://github.com/simplesteph/grpc-go-course/blob/master/ssl/instructions.sh
I followed the steps above to generate certificates. The server started successfully after loading the certificates generated.

What are the files generated from the link above that I have to load as Root Certificate, Private Key & Cert Chain in BloomRPC to make the connection successful?

Any documentation link on how to use this will be helpful.

![image](https://user-images.githubusercontent.com/49723661/61590199-acacd300-abd2-11e9-96d0-1847a36b784a.png)

Below is my gRPC server code.

`import io.grpc.ServerBuilder;
import user.UserService;

import java.io.File;
import java.io.IOException;

import io.grpc.Server;
import io.grpc.protobuf.services.ProtoReflectionService;

public class gRPCService {
	public static void main (String [] args) throws IOException, InterruptedException {
		
		try {
			File cert = new File("ssl/server.crt");
			File key = new File("ssl/server.pem");
			
			Server server = ServerBuilder.forPort(9091)
					.useTransportSecurity(cert, key)
					.addService(ProtoReflectionService.newInstance())
					.addService(new UserService())
					.build();
			
			server.start();
			
			System.out.println("Server started at " + server.getPort());
			
			server.awaitTermination();
		} catch (Exception e) {
			System.out.println("Server started at " + e);
			e.printStackTrace();
		}
	}
}`

**Comment by fenos** [comment] 2019-07-23 08:37
@mohanavijay Hi!

It should be the following: 
- `ca.crt` Root Certificate
- `ca.key` Private Key
- `server.csr` Cert Chain

This is standard mutual TLS with gRPC let me know if this worked for you

**Comment by mohanavijay** [comment] 2019-07-23 15:24
@fenos,

It's not working. I'm getting the below error. Can I leave the **ssl target host** as empty?

```
{
  "error": "14 UNAVAILABLE: channel is in state TRANSIENT_FAILURE"
}
```

Also, whenever I **Add Root Certificate**. A new row is created on the TLS/SSL Manager window. (Please refer screenshot). This looks like an issue.

![image](https://user-images.githubusercontent.com/49723661/61724208-1c65be00-ad8b-11e9-8968-7c592c9dfcd0.png)

**Comment by fenos** [comment] 2019-07-26 08:32
@mohanavijay Yes the UI issue will be fixed coming release.

regarding the `ssl target host` should be the hostname which you generated the ssl certificate for `localhost` in case of the script

**Comment by fenos** [comment] 2019-07-26 08:33
@mohanavijay if you can create an issue with the UI bug will be appreciated

**Comment by mohanavijay** [comment] 2019-07-26 11:40
@fenos, I have created a new issue #103 for the Duplicate rows in TLS / SSL Manager Interface.

I'm using `localhost` as `ssl target host`. I'm not able to connect using TLS.
Can you please give this a try and let me know what I'm missing or is this a bug?

**Comment by fenos** [comment] 2019-07-26 15:16
@mohanavijay Alright i made it work! Sorry for the confusion above but those are the files you'll need to use:

- server.crt Root Certificate
- server.pem Private Key
- server.csr Cert Chain

The steps i've done to reproduce this working scenario are:

## Steps

1 - Installing `bloomrpc-mock` to have a quick `grpc server` running 
(you can skip this since you have your server) 
```
npm install bloomrpc-mock -g
```

2 - I created a test.proto file for testing propose that looks as following:

**test.proto**
```proto
syntax = "proto3";

package test;

message Test {
  string id = 1;
}

message TestRequest {

}

message TestResponse {
  string message = 1;
}

service ItemRepository {
  rpc TestMethod(TestRequest) returns (TestResponse);
}
```

3 - Created the cert files using the script you linked `./gen_certs.sh` and locate them into a `certs` directory

4 - Started the **test** server with a secure connection 
```
bloomrpc-mock test.proto -r ./certs/server.crt -k ./certs/server.pem,./certs/server.crt
```
5 - Went to bloomrpc UI and loaded the certificate in the order i mentioned above 

<img width="748" alt="Screenshot 2019-07-26 at 16 15 46" src="https://user-images.githubusercontent.com/4754064/61962065-a5b20600-afc0-11e9-9ca3-2e44aa6fe675.png">

Hit Play!

🎉

**Comment by mohanavijay** [comment] 2019-07-26 16:32
@fenos,
Thank you for checking this!
I can confirm that this works when I use **bloomrpc-mock gRPC server**.
This doesn't work with my gRPC Java server. I'm getting the error below.
Does Bloomrpc require Server to be configured for Mutual TLS authentication?
Please refer -> https://github.com/grpc/grpc-java/blob/master/SECURITY.md

```
{
  "error": "14 UNAVAILABLE: Connect Failed"
}
```

Below is my server code.

```
public class gRPCService {
	public static void main (String [] args) throws IOException, InterruptedException {
		
		try {
			File cert = new File("ssl/server.crt");
			File key = new File("ssl/server.pem");
			
			Server server = ServerBuilder.forPort(9092)
					.useTransportSecurity(cert, key)
					.addService(ProtoReflectionService.newInstance())
					.addService(new UserService())
					.addService(new AlarmService())
					.build()
					.start();
			
			System.out.println("Server started at " + server.getPort());
			
			server.awaitTermination();
		} catch (Exception e) {
			System.out.println("Server started at " + e);
			e.printStackTrace();
		}
	}
}

```

**Comment by fenos** [comment] 2019-07-30 08:23
@mohanavijay Hi i gave it another shot.

Unfortunately i can't use your server code, but i tried the exact equivalent for a GO server and it does work for me.

here is what i've done:

### Go Server with TSL

#### Server - main.go

```go
package main

import (
	"context"
	"fmt"
	"github.com/utilitywarehouse/grpc-tsl-test/generated"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials"
	"net"
)

var (
	crt = "certs/server.crt"
	key = "certs/server.pem"
)

func main() {
	err := Serve(":8088")

	if err != nil {
		fmt.Println(err)
	}
}

type TestService struct {}

func (t *TestService) TestMethod(context.Context, *protos.TestRequest) (*protos.TestResponse, error) {

	return &protos.TestResponse{
		Message: "Hello3",
	}, nil
}

func Serve(addr string) error {

	// Create the channel to listen on
	lis, err := net.Listen("tcp", addr)
	if err != nil {
		return fmt.Errorf("could not list on %s: %s", addr, err)
	}

	// Create the TLS credentials
	creds, err := credentials.NewServerTLSFromFile(crt, key)
	if err != nil {
		return fmt.Errorf("could not load TLS keys: %s", err)
	}

	// Create the gRPC server with the credentials
	srv := grpc.NewServer(grpc.Creds(creds))

	// Register the handler object
	protos.RegisterTestServiceServer(srv, &TestService{})

	// Serve and Listen
	if err := srv.Serve(lis); err != nil {
		return fmt.Errorf("grpc serve error: %s", err)
	}

	return nil
}
```

Server will run on port `8088`

#### Proto file
```proto
syntax = "proto3";

package test;

message Test {
  string id = 1;
}

message TestRequest {

}

message TestResponse {
  string message = 1;
}

service TestService {
  rpc TestMethod(TestRequest) returns (TestResponse);
}
```

This were my TSL settings in bloomrpc

<img width="749" alt="Screenshot 2019-07-30 at 09 22 06" src="https://user-images.githubusercontent.com/4754064/62112907-89a5b180-b2ab-11e9-803b-654c3d420ad0.png">

The request was successful! 

Please try to give another try using the above settings in bloomrpc with your server

**Comment by fenos** [comment] 2019-07-31 07:51
Closing for now since I couldn’t reproduce it. 

let me know if at the end it worked for you

**Closed by fenos** 2019-07-31 07:51 UTC

**Comment by mohanavijay** [comment] 2019-08-09 09:12
@fenos,

I was finally able to make this work after generating the certificates using the below command.
openssl req -x509 -newkey rsa:4096 -keyout /Users/vijay/gRPC/my-private-key.pem -out /Users/vijay/gRPC/my-public-key-cert.pem -days 365 -nodes -subj '/CN=localhost'

Then in BloomRPC, I loaded the certs using as below

![image](https://user-images.githubusercontent.com/49723661/62768015-8bddec00-bab3-11e9-8cbe-af997473e8ed.png)

**Comment by manasyadav** [comment] 2020-05-06 03:35
Why do we need the server's private key on the client-side to make a request? Am I missing something?

**Comment by leftbin-swarup** [comment] 2021-08-28 20:27
i was able to use grpc_health_probe to check the health of the service

```shell
ghp -addr grpc.app.local:443 --tls-no-verify
```

i can not connect to the same service using bloomrpc. based on the above, i need to load server certificate on the client to make the request? that sounds wrong to me.

**Comment by SirBarksALot** [comment] 2021-09-14 13:42
> i was able to use grpc_health_probe to check the health of the service
> 
> ```shell
> grpc_health_probe -addr grpc.app.local:443 --tls-no-verify
> ```
> 
> i can not connect to the same service using bloomrpc. based on the above, i need to load server certificate on the client to make the request? that sounds wrong to me.

Same here, specifying cert to connect with is weird, it shouldn't work like this. Server we are connecting to is giving us its public key and we are signing data with it so only server (priv key holder) can read it. Can we somehow support on client side (bloomrpc) something like this (Go client)
``` go
tc := credentials.NewTLS(&tls.Config{
	InsecureSkipVerify: true,
	})
conn, err := grpc.Dial(address, grpc.WithTransportCredentials(tc), grpc.WithBlock())
```

**Comment by freynder** [comment] 2022-11-12 16:50
The whole SSL part of the UI is extremely confusing. I lost a lot of time trying to make this work with a self signed certificate. The SSL UI part is unintuitive and does not show any error details when the connection fails, so it's really difficult to understand what is happening.
For what it's worth, I checked the code and a quick interpretation with regards to the SSL UI part is like this:
- Selecting the first checkbox, which is basically next to the headers, disables TLS
- Selecting "Server Certificate" connects using standard TLS negotation. Note that server certs that do not validate to a known root CA will probably fail to connect.
- Adding your own root certificate requires setting the "Root Certificate" column. The private Key, Cert Chain and SSL target host fields may remain empty. These parameters seem to be mapped directly to the client creation with creds parameter constructed using a function mapping these parameters: [grpc.credentials](https://grpc.github.io/grpc/node/grpc.credentials.html#.createSsl__anchor) . Not fully clear how that works, but I would assume that the "Root Certificate" pem may contain multiple root CA certs? The private key and cert chain fields are for Client authentication purposes. The ssl target host is mapped to 'grpc.ssl_target_name_override' which I assume overrides the hostname during TLS negotation.
