### ISSUE TITLE
Cannot handle big files 

### ISSUE THREAD

**Issue by xbitres** [uw-labs/bloomrpc#52] opened 2019-03-18 17:11 UTC
I have a 23Kb proto file that contains two dependencies, one with 171 bytes and the other with 9 Kb. Unfortunately I am not able to share the proto file

When I try to import this file I get the following error:
![Screenshot 2019-03-18 at 17 06 51](https://user-images.githubusercontent.com/7966229/54548862-bca47400-49a0-11e9-9259-443206b2bc44.png)

Is it possible to increase the call stack size based on the computer? 

This issue makes it really difficult to use bloomrpc in an enterprise environment.

**Comment by fenos** [comment] 2019-03-20 09:19
@xbitres thanks for reporting this, can you share some protofile to reproduce the issue? I also have some guess on how to solve this,

**Comment by xbitres** [comment] 2019-03-20 11:55
I tried to make a sample file but I could not due it. I think it is because the file that is giving me errors has a lot of fields that are references to other types of message and this is not easily reproducible in a test

**Comment by fenos** [comment] 2019-03-20 12:01
I've made some improvements on recents PR on how the proto are parsed. I'd love you to try to build the code form source and see if you still have the same problem, alternatively i'll be doing a beta release tomorrow or friday

**Comment by xbitres** [comment] 2019-03-20 22:02
I will try to do it.

**Comment by fenos** [comment] 2019-03-23 10:31
Hi release 1.30-alpha is now available [Here](https://github.com/uw-labs/bloomrpc/releases/tag/untagged-1d775e54a409ccd4b085) could you try to load the protos and see if they get parsed successfully now, Thanks

**Comment by xbitres** [comment] 2019-03-23 11:55
@fenos the link leads to a 404 page.

**Comment by fenos** [comment] 2019-03-23 11:57
oh sorry, check the release page: https://github.com/uw-labs/bloomrpc/releases

you will find the installer for the version 1.3-alpha

**Comment by xbitres** [comment] 2019-03-23 12:03
I am sorry but I can only see the version 1.2.1 there

**Comment by fenos** [comment] 2019-03-23 12:24
Ah, I see draft releases are just shown me, i published it now. You should be able to see it now

**Comment by xbitres** [comment] 2019-03-25 12:58
I just tried to import the file in the 1.3 alpha build and I did not get the same error as before. However, On the left page, the proto file does not display any methods.

![Screenshot 2019-03-25 at 12 58 01](https://user-images.githubusercontent.com/7966229/54921442-b01e9f00-4efd-11e9-8f42-448fac668f65.png)

**Comment by fenos** [comment] 2019-03-26 09:12
@xbitres ok, 1 step forward i guess 😄 

Mmmh that is strange, it usually happens when you don't have a `service` definition in the imported proto file, can you confirm that you have a `service` with methods?

**Comment by xbitres** [comment] 2019-03-26 09:54
I can confirm that I have a service with 8 rpc methods.

**Comment by fenos** [comment] 2019-03-26 10:02
Mmmmh ok, it's difficult for me to guess what the problem can be, do you notice anything suspicious in your proto definition? Shall we have a slack session and try to fix the issue together?  

Without the protofile i'm unable to debug unfortunately

**Comment by fenos** [comment] 2019-05-03 15:29
Closing since I **Can't reproduce** this.

I'll be glad to have this fixed if it's still an issue with future versions

**Closed by fenos** 2019-05-03 15:29 UTC
Labels: bug, need reproduction
